# Generated by Django 5.2.8 on 2025-12-06 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_state_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndigenousUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_tier', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('INSTITUTIONAL', 'Institutional')], default='PENDING', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='app.land')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indigenous_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indigenous User',
                'verbose_name_plural': 'Indigenous Users',
                'indexes': [models.Index(fields=['land', 'verification_tier'], name='app_indigen_land_id_b0a1ae_idx')],
            },
        ),
    ]
