# Generated by Django 5.2.8 on 2025-12-06 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_indigenoususer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VouchingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_validators', models.PositiveIntegerField(default=2, help_text='Minimum approvals needed for verification')),
                ('rejection_cooldown_days', models.PositiveIntegerField(default=30, help_text='Days to wait after rejection before requesting again')),
                ('vouching_request_expiry_days', models.PositiveIntegerField(default=30, help_text='Days before vouching request expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vouching_config', to='app.land')),
            ],
            options={
                'verbose_name': 'Vouching Configuration',
                'verbose_name_plural': 'Vouching Configurations',
            },
        ),
        migrations.CreateModel(
            name='Vouching',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from requester')),
                ('validator_response', models.TextField(blank=True, help_text='Response from validator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouching_requests', to='app.indigenoususer')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouching_validations', to='app.indigenoususer')),
            ],
            options={
                'verbose_name': 'Vouching Request',
                'verbose_name_plural': 'Vouching Requests',
                'indexes': [models.Index(fields=['requester', 'status'], name='app_vouchin_request_046aba_idx'), models.Index(fields=['validator', 'status'], name='app_vouchin_validat_acafb9_idx')],
                'unique_together': {('requester', 'validator')},
            },
        ),
    ]
